module.exports = {
  AUTH: `/auth`,
  USER: `/user`,
  ADMIN: `/admin`,
  ROLE: `/role`,
  MODEL: `/model`,
  PROJECT: `/project`,
  BOOKING: `/booking`,
  TRANSACTION: `/transaction`,
  BOOK: `/book`,
  CATEGORY: `/category`,
  TAG: `/tag`,
  BLOG: `/blog`,
  MEETING: `/meeting`,
  SEARCH: '/search',
  SUBSCRIPTION: `/Subscribe`,
  SCHEDULE: '/schedule',
  EVENTS: '/event',
  CONTACT: '/contact',
  NOTIFICATION: '/notification',
  COMMISSION: '/commission',

  AUSSTATTUNG: "/ausstattung",
  BEVERAGES: "/beverage",
  CATERING: "/caterings",
  DEKORATION: "/dekoration",
  EVENTMODULE: "/eventmodule",
  HOTELMANAGEMENT: "/hotelmanagement",
  LOCATION: "/location",
  PRASENTE: "/prasente",
  SHUTTLE: "/shuttle",
  STAFF: "/staff",
  VERANST: "/veranstaltungstechnik",

  CITY:"/city",
  EVENT:"/event",
  RANGE:"/range",
  ORDER:"/order",
};
